version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/openebs/scope-plugin5
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: make
      - run: docker tag openebs/scope-plugin:latest pradeepkumar95/iops:ci
      - run: go get -u golang.org/x/lint/golint
      - run: golint
      - run: go test ./...
      - run: go fmt ./...
  deploy:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/openebs/scope-plugin5
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          test -z "${DOCKER_USER}" && exit 0
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          for IMAGE in $(./tools); do
            docker tag openebs/scope-plugin:latest pradeepkumar95/iops:ci
            docker push pradeepkumar95/iops:ci
          done
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
    