defaults: &defaults
  working_directory: /go/src/github.com/openebs/scope-plugin5
  docker:
    - image: circleci/golang:1.9
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: make
      - run: go get -u golang.org/x/lint/golint
      - run: golint
      - run: go fmt ./...
      - persist_to_workspace:
          root: .
          paths:
          - plugin.tar
  unit-test:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - run: ./hack/coverage.sh
      - run: bash <(curl -s https://codecov.io/bash) CODECOV_TOKEN
  deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run: docker load -i plugin.tar
      - run: |
          test -z "${DOCKER_USER}" && exit 0
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag openebs/scope-plugin:ci pradeepkumar95/iops:ci
          docker push pradeepkumar95/iops:ci
  deploy1:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run: docker load -i plugin.tar
      - run: |
          test -z "${DOCKER_USER}" && exit 0
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag openebs/scope-plugin:ci pradeepkumar95/iops:staging
          docker push pradeepkumar95/iops:$(./tools/image-tag)
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - unit-test
          filters:
            branches:
              only: master
      - deploy1:
          requires:
            - build
            - unit-test
          filters:
            branches:
              only: staging
    