defaults: &defaults
  working_directory: /go/src/github.com/openebs/scope-plugin5
  docker:
    - image: circleci/golang:1.9
version: 2
jobs:
  build:
    <<: *defaults
    # docker:
    #   - image: circleci/golang:1.9
    # working_directory: /go/src/github.com/openebs/scope-plugin5
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: make
      - run: go get -u golang.org/x/lint/golint
      - run: golint
      - run: go test ./...
      - run: go fmt ./...
  deploy:
    <<: *defaults
    # docker:
    #   - image: circleci/golang:1.9
    # working_directory: /go/src/github.com/openebs/scope-plugin5
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: |
          test -z "${DOCKER_USER}" && exit 0
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          for IMAGE in $IMAGES; do
              docker tag openebs/scope-plugin:ci pradeepkumar95/iops:ci
              docker push pradeepkumar95/iops:ci
          done
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
    