version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: ~/go/src/github.com/openebs/scope-plugin1
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: make 
      - run: make test
      - run: make lint
      - run: make fmt


# machine:
#   services:
#     - docker
#   environment:
#     GOPATH: /home/ubuntu
#     SRCDIR: /home/ubuntu/scope-plugin
#     PATH: $PATH:$HOME/.local/bin

# dependencies:
#   cache_directories:
#     - "~/docker"
#   override:
#     - echo "no dependencies"

# test:
#   override:
#     - cd $SRCDIR && make .iops.uptodate && docker tag weaveworksplugins/scope-iops pradeepkumar95/scope-plugin:$(./tools/image-tag)
#     - docker tag weaveworksplugins/scope-iops pradeepkumar95/scope-plugin:latest

# deployment:
#   stag:
#     branch: staging
#     commands:
#       - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
#       - docker push pradeepkumar95/scope-plugin:$(./tools/image-tag)
#   pro:
#     branch: master
#     commands:
#       - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
#       - docker push pradeepkumar95/scope-plugin:latest
