version: 2
defaults: &defaults
  working_directory: /go/src/github.com/openebs/scope-plugin5
docker:
      - image: circleci/golang:1.9
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
    
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: make
      - run: go get -u golang.org/x/lint/golint
      - run: golint
      - run: go test ./...
      - run: go fmt ./...
  deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          test -z "${DOCKER_USER}" && exit 0
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          for IMAGE in $IMAGES; do
              docker tag pradeepkumar95/$IMAGE:ci pradeepkumar95/$IMAGE:ci1
              docker push pradeepkumar95/$IMAGE:ci1
          done
# workflows:
#   version: 2
#   test_and_deploy:
#     jobs:
#       - build
#       - deploy:
#           filters:
#             branches:
#               only: master
#           requires:
#             - build
    