# defaults: &defaults
#   working_directory: /go/src/github.com/openebs/scope-plugin5
#   machine: 
#       docker_layer_caching: true
# version: 2
# jobs:
#   build:
#     <<: *defaults
#     steps:
#       - checkout
#       - setup_remote_docker
#       - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
#       - run: docker build -t pradeepkumar95/iops:latest .
#       - run: docker push pradeepkumar95/iops:latest


version: 2
jobs:
  build_tag_0:
    machine: 
      docker_layer_caching: true
    working_directory:  ~/github.com/Pradeepkumarbk/istgt
    steps:
      - checkout
      # - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t pradeepkumar95/cstor-base:ci .
      - run: docker push pradeepkumar95/cstor-base:ci
workflows:
  version: 2
  TAGS:
    jobs:
      - build_tag_0